# fly.preprod.toml app configuration file for pre-production environment
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'speaking-preprod-meetingbaas'
primary_region = 'cdg'

[build]

[env]
  PORT = '8766'
  API_URL = 'https://api.pre-prod-meetingbaas.com'

[http_service]
  internal_port = 8766
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.domains]]
  name = "speaking.pre-prod-meetingbaas.com" 
  zone = "pre-prod-meetingbaas.com"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
